-- Flyway Migration: V1 - Initial Schema
-- Bu migration dosyası projenin temel veritabanı şemasını oluşturur

-- ============================================
-- 1. ROLES TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- ============================================
-- 2. USERS TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

-- ============================================
-- 3. USER ROLES (JOIN TABLE)
-- ============================================
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- ============================================
-- 4. CATEGORIES TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================
-- 5. SOURCES TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    base_url VARCHAR(255),
    category_path VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    crawl_url VARCHAR(500),
    title_selector VARCHAR(200),
    content_selector VARCHAR(200),
    link_selector VARCHAR(200),
    crawl_type VARCHAR(50),
    last_minute_url VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL
);

-- ============================================
-- 6. NEWS TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INTEGER NOT NULL,
    external_id VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    content TEXT,
    original_url VARCHAR(500),
    language VARCHAR(10) DEFAULT 'tr',
    published_at TIMESTAMP(6),
    fetched_at TIMESTAMP(6) NOT NULL,
    is_processed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_news_source FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE CASCADE
);

-- ============================================
-- 7. NEWS CATEGORIES (JOIN TABLE)
-- ============================================
CREATE TABLE IF NOT EXISTS news_categories (
    news_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,
    PRIMARY KEY (news_id, category_id),
    CONSTRAINT fk_news_categories_news FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    CONSTRAINT fk_news_categories_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- ============================================
-- 8. MODEL VERSIONS TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS model_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    CONSTRAINT fk_model_versions_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================
-- 9. NEWS CLASSIFICATION RESULTS TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS news_classification_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id BIGINT NOT NULL,
    model_version_id INTEGER NOT NULL,
    predicted_category_id INTEGER NOT NULL,
    prediction_score NUMERIC(5,4),
    classified_at TIMESTAMP(6) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_classification_results_news FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    CONSTRAINT fk_classification_results_model FOREIGN KEY (model_version_id) REFERENCES model_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_classification_results_category FOREIGN KEY (predicted_category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- ============================================
-- 10. CRAWLING LOGS TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS crawling_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INTEGER NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    finished_at TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,
    fetched_count INTEGER,
    error_message TEXT,
    CONSTRAINT fk_crawling_logs_source FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE CASCADE
);

-- ============================================
-- 11. USER FEEDBACK TABLESU
-- ============================================
CREATE TABLE IF NOT EXISTS user_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    model_version_id INTEGER,
    current_predicted_category_id INTEGER,
    user_selected_category_id INTEGER NOT NULL,
    feedback_type VARCHAR(20) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_feedback_news FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_feedback_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_feedback_model FOREIGN KEY (model_version_id) REFERENCES model_versions(id) ON DELETE SET NULL,
    CONSTRAINT fk_user_feedback_current_category FOREIGN KEY (current_predicted_category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_user_feedback_selected_category FOREIGN KEY (user_selected_category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- ============================================
-- INDEXES
-- ============================================
-- Users indexes
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- News indexes
CREATE INDEX IF NOT EXISTS idx_news_source_id ON news(source_id);
CREATE INDEX IF NOT EXISTS idx_news_fetched_at ON news(fetched_at);
CREATE INDEX IF NOT EXISTS idx_news_is_processed ON news(is_processed);
CREATE INDEX IF NOT EXISTS idx_news_created_at ON news(created_at);

-- Classification results indexes
CREATE INDEX IF NOT EXISTS idx_classification_results_news_id ON news_classification_results(news_id);
CREATE INDEX IF NOT EXISTS idx_classification_results_category_id ON news_classification_results(predicted_category_id);
CREATE INDEX IF NOT EXISTS idx_classification_results_model_id ON news_classification_results(model_version_id);

-- Crawling logs indexes
CREATE INDEX IF NOT EXISTS idx_crawling_logs_source_id ON crawling_logs(source_id);
CREATE INDEX IF NOT EXISTS idx_crawling_logs_started_at ON crawling_logs(started_at);
CREATE INDEX IF NOT EXISTS idx_crawling_logs_status ON crawling_logs(status);

-- User feedback indexes
CREATE INDEX IF NOT EXISTS idx_user_feedback_news_id ON user_feedback(news_id);
CREATE INDEX IF NOT EXISTS idx_user_feedback_user_id ON user_feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_user_feedback_model_id ON user_feedback(model_version_id);

